### ISSUE TITLE
Bug in Environment Initialization with Direct Role Assignment Causes Error

### ISSUE THREAD

**Issue by iphysresearch** [geekan/MetaGPT#1145]
**Bug description**

我看到Environment中也初始化参数也可以直接定义Role进去，所以我就试了下（因为我目标要实现多个不同的环境下的不同Team要协作），结果发现直接Bug报错。目测Bug的来源我还不太确定，因为我不太熟悉这个类的构造方式。根据下面截图的报错，可能是在 self.roles 赋值的时候，触发了什么机制保护？

**Bug solved method**

如上。

**Environment information**

- LLM type and model name:
    - gpt-4-1106-preview
- System version:
```text
# Inside a docker container
Linux e24f4ba5e757 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
- Python version:
    - Conda Python 3.10.13
- MetaGPT version or branch:
    - 0.8.0

- packages version:
- installation method: 
```shell
pip install -e . && pip install -e .[rag]
```

**Screenshots or logs**

![image](https://github.com/geekan/MetaGPT/assets/14322948/968b34f3-4692-48ed-9796-3cc7c0bc57f9)

**Comment by better629** [comment]
Maybe you can ref to `examples/debate_simple.py`, firstly init environment and then add `roles` into `team`. or, `Environment(desc="xxx", roles={assistant1.profile: assistant1, assistant2.profile: assistant2}) which due to the `roles` inside env is a dict that keys are `profile` of `role`.

BTW, I see you define a `android assistant`, what's your demands?

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
