### ISSUE TITLE
Resolving dependencies failed when using poetry

### ISSUE THREAD

**Issue by LAD021** [geekan/MetaGPT#1192]
Seems like metagpt requires qdrant-client == 1.7.0, numpy == 1.24.3, while qdant-client requires numpy >=1.26
![image](https://github.com/geekan/MetaGPT/assets/60390821/cc7456b7-bb5b-4e40-b6e0-fce3c2fe4817)
Here is my pyproject.toml
![image](https://github.com/geekan/MetaGPT/assets/60390821/7d56ca5c-4098-4aaa-964f-731f943b705c)

Maybe we can follow what langchain does, to isolate third-party dependencies like  `pip install langchain-openai`

**Comment by seehi** [comment]
Qdrant is not in use, may be removed in the future. FYI: [related issue](https://github.com/geekan/MetaGPT/issues/1171).

**Comment by LAD021** [comment]
> Qdrant is not in use, may be removed in the future. FYI: [related issue](https://github.com/geekan/MetaGPT/issues/1171).

It seems this lib belongs to an example, may be we can isolate the libs required by examples or specified tools (like search api) from main dependencies.

**Comment by kilesk** [comment]
I also encounter the same issue when trying to bring in MetaGPT as a dependency. The issue here is that purely using requirements.txt does not properly check dependency compatibility across packages (as is evident in this case).  

The other issue is the practice of locking popular python packages (such as pydantic) down to a specific version, as opposed to a compatible version range. This severely limits the ability to bring in other 3rd party libraries which also rely on these dependencies. 

For example if we were to look to langchain for how to best go about things:

```
numpy = "^1"
pydantic = ">=1,<3"
```

as compared to being locked down to specific versions as is the case in the current requirements.txt:

```
numpy==1.24.3
pydantic==2.5.3
```

Note: The original issue has been present since v0.7.1.

**Comment by LAD021** [comment]
What about using poetry or rye as a package management tool?

**Comment by geekan** [comment]
@seehi

**Comment by kilesk** [comment]
> What about using poetry or rye as a package management tool?

I'd definitely recommend poetry as a candidate, its what I use currently and it seems to be used a fair bit nowadays.

**Comment by liushuaikobe** [comment]
Has this issue been resolved? I meet the same issue when install the lastest `0.8.1` with poetry.

```
Because qdrant-client (1.7.0) depends on numpy (>=1.26)
 and metagpt (0.8.0) depends on numpy (1.24.3), qdrant-client (1.7.0) is incompatible with metagpt (0.8.0).
So, because metagpt-startup depends on metagpt (0.8.0) which depends on qdrant-client (1.7.0), version solving failed.
```

**Comment by michael-hedgineer** [comment]
I had to use pip and python 3.9. Even had issues installing with 3.12 & pip. qdrant-client was blocking any variation when trying to poetry install.

**Comment by Umpire2018** [comment]
For now, temporary solution would be `poetry add git+https://github.com/geekan/MetaGPT.git`.
