### ISSUE TITLE
Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 65.188(s), this was the 1st time calling it. exp: string index out of range

### ISSUE THREAD

**Issue by ghost** [geekan/MetaGPT#1321]
<img width="719" alt="image" src="https://github.com/geekan/MetaGPT/assets/157960305/07a25f75-110d-4dd6-95fe-5c11a6237948">

**Comment by NormanCarrie** [comment]
这个错误频繁出现

**Comment by NormanCarrie** [comment]
<img width="698" alt="image" src="https://github.com/geekan/MetaGPT/assets/157960305/bbdab81b-ffcb-40f4-9e69-05b6f94218ec">
还有这个错误，经常性会遇到

**Comment by better629** [comment]
Suggest to try a large LLM model, it gets better experience.

**Comment by maxin9966** [comment]
@better629 qwen2.5-72b还不够大吗？

**Comment by maxin9966** [comment]
@better629 qwen2.5全系列我都试了，百分百报这个错误，5次重试后任务失败

**Comment by better629** [comment]
due to we ask llm to output in json format and sometimes it not always works, maybe you can add `repair_llm_output: true` refs to `https://docs.deepwisdom.ai/main/en/guide/tutorials/integration_with_open_llm.html#main-issues-with-open-source-model-command-output`. And, BTW, we have tested deepseek, maybe you can also have a try.  @maxin9966
