### ISSUE TITLE
How to check total cost use

### ISSUE THREAD

**Issue by phanchauthang** [geekan/MetaGPT#1325]
Hello MetaGPT, i have use metaGPT many time and it save to one 1 log with many project i have create, so how can i check total cost and token use in each project, thanks you so much.

**Comment by usamimeri** [comment]
For now, MetaGPT will calculate the cost each time calling the API and the cost will be accumulated when running a project. The cost of one project is the last cost calculation message in the log. 
Since the log of different project may be saved to the same log.txt like 20240605.txt and the calculation will be mixed. 
you can use `grep "Total running cost" -n path/to/your_log.txt` to manually extract the cost.

**Comment by usamimeri** [comment]
@garylin2099 Is it able to set the log_name for a particular project?

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
