### ISSUE TITLE
git gc should be excuted by metagpt owner

### ISSUE THREAD

**Issue by CoderYiFei** [geekan/MetaGPT#1529]
<img width="647" alt="截屏2024-10-22 10 48 03" src="https://github.com/user-attachments/assets/261703b6-0881-4ae6-a719-b3235a17ec25">

metagpt 's .git directory is too large .
its better to excute git gc , to reduce .git directory data

**Comment by voidking** [comment]
The .git directory is very large, mainly caused by two historical files:
- docs/resources/tasks.mp4
- examples/ags/benchmark/data/hotpot.json

1. `git gc` does not work because the command is only applicable to local project cleanup and cannot be pushed to remote projects, so it has no effect on remote projects.
2. Moreover, `git gc` has limited effects. It mainly compresses objects and deletes unreachable objects, and is powerless for large historical files.

**Comment by voidking** [comment]
![image](https://github.com/user-attachments/assets/4e1ed0ee-d8a2-4bbc-8ab7-e42e906d6ca3)

Using git-filter-repo can achieve project slimming, and the .git directory can be reduced by about 100M after slimming.

However, there are risks here: after executing the slimming-related commands, the hash values ​​of all commit records will be rewritten (inevitable because the historical files have changed), and the hash rewriting has two main effects:
1. All forks need to be re-synced
2. All cloned projects can no longer be pulled directly, but need to be forced to overwrite the pull

To reduce 100M, it may cause problems for tens of thousands of users, which I don't think is worth it.
