### ISSUE TITLE
bug in MetaGPT-AFlow

### ISSUE THREAD

**Issue by sssjjjrrr6435** [geekan/MetaGPT#1549]
**Bug description**

Maximum retries reached. Skipping this sample. Error: module'metagpt.ext,aflow.scripts.optimized.HotpotoA.workflows.round_2.prompt' has no attribute 'XXX_PROMPT'
**Bug solved method**
还没解决

**Environment information**

- LLM type and model name:gpt-4o-mini，gpt-4o
- System version:windows11
- Python version:python3.9
- MetaGPT version or branch:didiforgithub/MetaGPT-AFLow

- packages version:
- installation method: 

**Screenshots or logs**

![image](https://github.com/user-attachments/assets/26d79186-fb22-4574-bb77-23825714b6e8)

自动产生的prompt.py文件
![image](https://github.com/user-attachments/assets/c37d0303-ff75-40a0-89a7-68215e7e54d2)

**Comment by geekan** [comment]
@didiforgithub can you take a look at this question?

**Comment by XiangJinyu** [comment]
Thank you for trying AFLOW. The issue you encountered is likely because the generated prompt wasn't correctly referenced by the Workflow. This error may occur with gpt-4, possibly due to the model's capabilities. If you want to avoid this issue, you can try modifying the prompt file for round_1 or switch to claude-3.5-sonnet. However, you don't necessarily need to worry about it, as these errors tend to self-correct during the iteration process.😊

**Comment by didiforgithub** [comment]
I submitted a PR: https://github.com/geekan/MetaGPT/pull/1552 to resolve the Max Retry Error. You can refer to [XiangJinyu](https://github.com/XiangJinyu) for the solution regarding the XXX_PROMPT error.

**Comment by geekan** [comment]
@sssjjjrrr6435 Can you try the latest version?

**Comment by sssjjjrrr6435** [comment]
> @sssjjjrrr6435 Can you try the latest version?

i will take a look

**Comment by jkkjjj** [comment]
I also encounter the same problem.
