### ISSUE TITLE
Why have a dependency on npm 

### ISSUE THREAD

**Issue by romechenko** [geekan/MetaGPT#167]
Is there a really good reason to keep a dependency on npm? Is the package just that good?

My Take: The library is more flexible as just python

**Comment by voidking** [comment]
Currently we use mermaid(nodejs) to generate image and pdf etc. If there is a better option in python, we will consider using it.

**Comment by dahifi** [comment]
GPT is trained on Mermaid, and it's what others are using. What alternatives did you have in mind? 

If you don't need image/pdfs then maybe it'd be better to just have it fail gracefully, but I'd take a look at maybe doing something like this: https://mermaid.js.org/config/Tutorials.html#jupyter-integration-with-mermaid-js

**Comment by ImJohnDoe** [comment]
Those seem like good reasons to use Mermaid. 

It sounds like you have two suggestions

  1. Add an option to not use Mermaid and make it fail gracefully wherever it’s used
  2. Use the [Mermaid.ink](https://mermaid.ink/) service to generate charts
  
Option 2. is nice because it solves my problem and eliminates the need for npm entirely. But it does rely on a free service that could be changed.

I like the idea of a combination of both options. Allow for disabling npm and falling back on using mermaid.ink

Any thoughts?

```
graph LR;
    A--> B & C & D;
    B--> A & E;
    C--> A & E;
    D--> A & E;
    E--> B & C & D;
```

![image](https://mermaid.ink/img/Z3JhcGggTFI7CiAgICBBLS0+IEIgJiBDICYgRDsKICAgIEItLT4gQSAmIEU7CiAgICBDLS0+IEEgJiBFOwogICAgRC0tPiBBICYgRTsKICAgIEUtLT4gQiAmIEMgJiBEOw==)

**Comment by voidking** [comment]
Good idea!

**Comment by ImJohnDoe** [comment]
One downside is that it does not seem to support pdf output. It does support svg, png, and jpeg.
What is the pdf format used for? Is it just to give people options?

**Comment by ImJohnDoe** [comment]
Pull request opened here 
https://github.com/geekan/MetaGPT/pull/265

**Comment by better629** [comment]
Since no further responses are needed, we will close it. Please reopen it if necessary.
