### ISSUE TITLE
How to make MetaGPT write anything else except Python

### ISSUE THREAD

**Issue by universeroc** [geekan/MetaGPT#252]
I'm curious about what MetaGPT can do.
After I run it through configuration and some issues.
I found it can only write Python!

if not anyone help me to give a workable prompt. Thanks in advance.

**Comment by TaylorTheDeveloper** [comment]
Also came here to post the same question. You can be very explicit but python is always used.

**Comment by universeroc** [comment]
> Also came here to post the same question. You can be very explicit but python is always used.

Yes, even I told it: "Write a snake game in JavaScript, HTML, CSS", it seemed ignore my command always using Python :P

**Comment by ralaska** [comment]
Same as https://github.com/geekan/MetaGPT/issues/129. Currently looks like only Python is supported.

**Comment by MightEnlightenYou** [comment]
This is because it is pre-prompted very specifically to write python code in a particular way. I think you need to at least change the roles description for all the roles to either a code-language-neutral prompt or specify another language.

Although I don't fully understand how all the parts of this agent works, partly because I'm not a dev and partly because there's a lot of Chinese comments in the code
