### ISSUE TITLE
[Errno 21] Is a directory: '/app/metagpt/config/key.yaml'

### ISSUE THREAD

**Issue by TonyRen9825** [geekan/MetaGPT#270]
你好，这是我运行Demo时遇到的错误，请帮忙，感谢：

PS C:\Users\23921> docker run --rm `
>> --privileged `
>> -v /opt/metagpt/config/key.yaml:/app/metagpt/config/key.yaml `
>> -v /opt/metagpt/workspace:/app/metagpt/workspace `
>> metagpt/metagpt:v0.3.1 `
>> python startup.py "Write a cli snake game"
Traceback (most recent call last):
  File "/app/metagpt/startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager
  File "/app/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/app/metagpt/metagpt/roles/role.py", line 15, in <module>
    from metagpt.config import CONFIG
  File "/app/metagpt/metagpt/config.py", line 114, in <module>
    CONFIG = Config()
  File "/app/metagpt/metagpt/utils/singleton.py", line 21, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/app/metagpt/metagpt/config.py", line 43, in __init__
    self._init_with_config_files_and_env(self._configs, yaml_file)
  File "/app/metagpt/metagpt/config.py", line 96, in _init_with_config_files_and_env
    with open(_yaml_file, "r", encoding="utf-8") as file:
IsADirectoryError: [Errno 21] Is a directory: '/app/metagpt/config/key.yaml'

**Comment by iamuddeshya** [comment]
Same issue 
with open(_yaml_file, "r", encoding="utf-8") as file:
IsADirectoryError: [Errno 21] Is a directory: '/app/metagpt/config/key.yaml'

**Comment by iamuddeshya** [comment]
### Issue: IsADirectoryError: [Errno 21] Is a directory: '/app/metagpt/config/key.yaml'

### Environment:
- Using Docker Desktop

### Symptom:
Encountered an `IsADirectoryError` indicating that `key.yaml` is being treated as a directory, rather than a file.

### Diagnosis:
Upon investigation in Docker Desktop's file explorer, it appears that `key.yaml` is indeed being mounted as a directory rather than a YAML file.

### Solution:
1. **Navigate to the `config.yaml` File**: Go to the `app/metagpt` directory and open `config.yaml`.
   
2. **Add Your API Key**: Before making any changes, ensure that your API key is properly entered into `config.yaml`.

3. **Edit the Reference**: Find the string `"key.yaml"` in `config.yaml` and replace it with `"config.yaml"`.
   
After performing these steps, the issue was resolved and the application worked as expected.

### Explanation:
It seems that Docker Desktop may be mounting `key.yaml` as a directory. The above fix redirects the application to look for `config.yaml` instead, where the API key is now stored.

### Note:
Make sure your API key is securely stored in `config.yaml` before making these changes.

---

Hope this helps anyone encountering the same issue!

---

**Comment by voidking** [comment]
Please create `/app/metagpt/config/key.yaml` first.
```bash
docker run --rm metagpt/metagpt:v0.3.1 cat /app/metagpt/config/config.yaml > /opt/metagpt/config/key.yaml
```

**Comment by sourcecodehive** [comment]
The above command results in "permission denied". Any clue?

**Comment by seehi** [comment]
# Problem
Windows may encounter the following issues:
* "IsADirectoryError: [Errno 21] Is a directory: '/app/metagpt/config/key.yaml'"
* permission denied

# Solution
For Windows, you need to replace "/opt/metagpt" with a directory that Docker has permission to create, such as "D:\Users\x\demo"
